# Generated by Django 5.0.14 on 2026-09-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('legajo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('tutor', 'Tutor'), ('administrador', 'Administrador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='core.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_de_carga', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('resumen', 'Resumen'), ('parcial', 'Parcial'), ('final', 'Final')], max_length=20)),
                ('validacion', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponderaciones', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=20)),
                ('aula', models.CharField(max_length=20)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_apoyo', to='core.materia')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_apoyo', to='core.usuario')),
            ],
        ),
    ]
