# Generated by Django 5.0.14 on 2026-09-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre_y_apellido',
        ),
    ]
