# Generated by Django 5.0.14 on 2026-09-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_usuario_nombre_y_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='codigo_sysacad',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='id_sysacad',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
