# Generated by Django 5.0.14 on 2026-09-21 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_especialidad_codigo_sysacad_materia_id_sysacad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponderacion',
            name='valor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='ponderacion',
            constraint=models.UniqueConstraint(fields=('material', 'usuario'), name='ponderacion_unica_por_usuario_y_material'),
        ),
    ]
